name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

# jobs:
#   unit-tests:
#     uses: oclif/github-workflows/.github/workflows/unitTest.yml@main

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]

    name: Lint/Unit tests
    steps:
      - uses: actions/checkout@v3
      - name: Run linting rules and tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test
